### ISSUE TITLE
Shows "successfully subscribed to push notifications" on every page

### ISSUE THREAD

**Issue by duttakapil** [vinaypuppal/linklet-app#5]
![Page 3](https://cloud.githubusercontent.com/assets/6577624/25078750/cc5f9bd8-2353-11e7-8518-faa3882f1c64.png)

Just found out that clicking to any different page shows the "successfully subscribed to push notifications" message on the bottom left. 

![Page 4](https://cloud.githubusercontent.com/assets/6577624/25078785/13290ea0-2354-11e7-8ad6-278a26c9963c.png)

Browser : Firefox

**Comment by vinaypuppal** [comment]
its weird it only happens in firefox. I will debug and see if i can fix this.

**Comment by vinaypuppal** [comment]
@duttakapil Found the issue and fixed it 🎉 
Recheck and if still happens let me know.

**Do these before testing again**
- First unsubscribe from push notifications but it will fail and switch will still in `on` state only because it was not handled correctly first time when you subscribed.
- so refresh the page 
- Now you subscribe again
- And now every thing should work as expected

Actually what happened is on firefox we need to handle push subscription differently than chrome which i did not know at first, i fixed this in above commits.

**Comment by duttakapil** [comment]
Yup, it works fine now. Followed your instructions and it doesn't show anymore
