### ISSUE TITLE
Please insert link for android app for linklet

### ISSUE THREAD

**Issue by M-ZubairAhmed** [vinaypuppal/linklet-app#7]
I think it will be a good idea to include in the read me or links to include work is also being going on android app for the same as well.
here is the link

https://github.com/M-ZubairAhmed/Linklet-Android

**Comment by vinaypuppal** [comment]
For inserting links user need to be logged in using GitHub. For now I just implemented the API for web and I don't know how to do it for Android because I don't know what information you can provide me after login. What I need is GitHub access token inorder to create user in database which we get after successful user authentication with GitHub.if you can provide me that access token I can create an endpoint for you to login user.

I followed this guide.
https://developer.github.com/v3/oauth/#web-application-flow

**Comment by duttakapil** [comment]
@vinaypuppal while that would be a good idea, @M-ZubairAhmed is not talking about that. He is just suggesting that you add his Android project for Linklet in the README file of this repo

**Comment by M-ZubairAhmed** [comment]
@vinaypuppal yes as @duttakapil mentioned we will work on POST and authentication in android app soon, and for that i will open up the issue on linklet api.
For now please give a reference in readme of our android app link

**Comment by vinaypuppal** [comment]
Sorry I misread this issue. @M-ZubairAhmed Yeah we can add reference to your repo. Just send a PR to add this link.

**Comment by M-ZubairAhmed** [comment]
sure i will in a while, overburden with work at the moment

**Comment by vinaypuppal** [comment]
Closing this as i added link to your repo here https://github.com/vinaypuppal/linklet-app#community-ports
