### ISSUE TITLE
Ability to filter out duplicate links

### ISSUE THREAD

**Issue by M-ZubairAhmed** [vinaypuppal/linklet-app#9]
What do you guys think we should do with duplicate links ?
i just posted two same links and system accepted both? Can we have before taking in the db; a search and filter process?

**Comment by vinaypuppal** [comment]
There is already a duplicate links checking logic
But u posted two same links one with www and another without it. That's why both are saved to database. Anyway I will refine this logic more based on link metadata.

> Can we have before taking in the db; a search and filter process?

Yeah we can do that but one more case is urls ending with or without / . So I think it's better to use links metadata to detect duplicates at database level.

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed I fixed this on API side and deployed new version. Please check and close this issue if its solved. Thanks

**Comment by M-ZubairAhmed** [comment]
I still added two same links!

**Comment by vinaypuppal** [comment]
Hey just saw u inserted again but it was successful becoz before url has ending `/` and this does not and new API update removes ending `/` so if add again same link it should throw error.
![screen shot 2017-04-18 at 5 46 19 pm](https://cloud.githubusercontent.com/assets/8843216/25130190/f6b0e944-245e-11e7-8431-97c6ffd150f4.png)

See i tried to add same link again now it throws error. You may also try again.

**Comment by M-ZubairAhmed** [comment]
yes so i just checked with same link with and without / . it works.
Can you verify it too

**Comment by M-ZubairAhmed** [comment]
i tried all the combinations around the root url. all seems to work awesome!
